// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8CZVb49xBKNDspp5vlkQ1DD8zQVu9Wgw',
    appId: '1:914888057780:web:dd3348b3aa1f7e33f6c8e1',
    messagingSenderId: '914888057780',
    projectId: 'docfusion-30182',
    authDomain: 'docfusion-30182.firebaseapp.com',
    storageBucket: 'docfusion-30182.firebasestorage.app',
    measurementId: 'G-F6Y6YL7DC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIFmZ966E4e7CN-Cu2_CDVArQJC24D1Ng',
    appId: '1:914888057780:android:d3947d31dcb8919af6c8e1',
    messagingSenderId: '914888057780',
    projectId: 'docfusion-30182',
    storageBucket: 'docfusion-30182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWfS8_ql-jqyirCADu0ZtkdxRuAHFsL80',
    appId: '1:914888057780:ios:2034c3722e06d5fcf6c8e1',
    messagingSenderId: '914888057780',
    projectId: 'docfusion-30182',
    storageBucket: 'docfusion-30182.firebasestorage.app',
    iosBundleId: 'com.example.docFusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWfS8_ql-jqyirCADu0ZtkdxRuAHFsL80',
    appId: '1:914888057780:ios:2034c3722e06d5fcf6c8e1',
    messagingSenderId: '914888057780',
    projectId: 'docfusion-30182',
    storageBucket: 'docfusion-30182.firebasestorage.app',
    iosBundleId: 'com.example.docFusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8CZVb49xBKNDspp5vlkQ1DD8zQVu9Wgw',
    appId: '1:914888057780:web:b3cff334bc07ba7bf6c8e1',
    messagingSenderId: '914888057780',
    projectId: 'docfusion-30182',
    authDomain: 'docfusion-30182.firebaseapp.com',
    storageBucket: 'docfusion-30182.firebasestorage.app',
    measurementId: 'G-SCJ1H51MVX',
  );
}
